##TRACKING CONFIG
# ------------------- General Options -------------------------
description                  : AB3DMOT
seed                         : 0

# --------------- main.py
save_root                    : ./tracker_exp_local/KITTI/exp
dataset                      : KITTI      # KITTI
split                        : val        # val, test
det_name                     : det_link  # name of the detector [pointrcnn, pvrcnn]/ gt
cat_list                     : ['car'] #['Car', 'Pedestrian', 'Cyclist']
#--------------- SEQ
seq_eval                     : [1,2,5,7,8,9,11,18,19,20] #[1,2,5,7,8,9,11,18,19,20] #sequence to track, [] means by default
# --------------- model.py
ego_com                      : true      # turn on only slightly reduce speed but increase a lot for performance

#---------------- addition
label_format                 : Kitti      # Kitti, Waymo, nuscenes, AB3DMOT
label_coord                  : camera       # lidar or camera
buffer_size                  : 30
history                      : 1
output_kf_cls                : True ## if true output kf car as KF_Car class
output_mode                 : 'interpolate' ## output by interpolate or kf predict

# ------------------NDT
NDT_flag                     : True
pcd_db_root                  : "./data/KITTI/dense_db/dense_128_all/"
NDT_cfg                      : {'voxel_size': 0.5, 'overlap': True, 'min_pts_voxel': 5, 'noise': 0.05}
NDT_cache_root               : "./data/KITTI/NDT_pkl/"
NDT_cache_name               : "cache-128" #path for load/write

#---------------AB3DMOT base
use_default                  : False
base_param                   : {'car':{'algm': 'hungar', 'metric': 'giou_3d', 'thres': 0.2, 'min_hits': 1, 'max_age': 20},
                                'cyclist':{'algm': 'hungar', 'metric': 'dist_3d', 'thres': 2.5, 'min_hits': 1, 'max_age': 10}}         
# --------------- DA stage2 threshold
stage2_param                 : {'car': {'NDT_score': -20000,'max_dist': 6.0},
                                'cyclist': {'NDT_score': -20000,'max_dist': 4.0}}  

