##TRACKING CONFIG
# ------------------- General Options -------------------------
description                  : AB3DMOT
seed                         : 0

# --------------- main.py
save_root                    : ./tracker_exp_local/KITTI/exp
dataset                      : KITTI      # KITTI
split                        : val        # val, test
det_name                     : det_link  # name of the detector [pointrcnn, pvrcnn]/ gt
cat_list                     : ['car','cyclist'] #['Car', 'Pedestrian', 'Cyclist']

score_threshold              : -10000     # filter out tracklet with low confidence if necessary, default no filtering here but do it in trk_conf_threshold.py
num_hypo                     : 1          # >1 to allow multi-hypothesis tracking

# --------------- model.py
ego_com                      : true      # turn on only slightly reduce speed but increase a lot for performance
vis                          : false       # only for debug or visualization purpose, will significantly reduce speed
affi_pro                     : false
#---------------- addition
label_format                 : Kitti      # Kitti, Waymo, nuscenes, AB3DMOT
label_coord                  : camera       # lidar or camera
buffer_size                  : 10
history                      : 1
# ------------------NDT
NDT_flag                     : False
pcd_db_root                  : ""
NDT_cfg                      : {'voxel_size': 0.5, 'overlap': True, 'min_pts_voxel': 5, 'noise': 0.05}
NDT_out_path                 : ""
#---------------
seq_eval                     : [0,1,2,4,5,10,11,13,15,16] #sequence to track, [] means by default
#---------------AB3DMOT base
use_default                  : False
base_param                   : {'algm': 'hungar', 'metric': 'giou_3d', 'thres': 0.25, 'min_hits': 1, 'max_age': 5}

