##TRACKING CONFIG
# ------------------- General Options -------------------------
description                  : AB3DMOT
seed                         : 0

# --------------- main.py
save_root                    : ./tracker_exp_local/KITTI/exp
dataset                      : KITTI      # KITTI
split                        : val        # val, test
det_name                     : point_rcnn  # name of the detector [pointrcnn, pvrcnn]/ gt
cat_list                     : ['car'] #['Car', 'Pedestrian', 'Cyclist']
#--------------- SEQ
seq_eval                     : [1,2,5,7,8,9,11,18,19,20] #[1,6,8,10,12,13,14,15,16,18,19] #[1,2,5,7,8,9,11,18,19,20] #sequence to track, [] means by default
# --------------- model.py
ego_com                      : True      # turn on only slightly reduce speed but increase a lot for performance

#---------------- addition
label_format                 : Kitti      # Kitti, Waymo, nuscenes, AB3DMOT
label_coord                  : camera       # lidar or camera
buffer_size                  : 30
history                      : 1
output_kf_cls                : True ## if true output kf car as KF_Car class
output_mode                  : 'kf' ## output by interpolate or kf predict
kf_initial_speed             : 30 #km/h
conf_thres                   : 1.0 
# ------------------NDT
NDT_flag                     : True
pcd_db_root                  : "./data/KITTI/dense_db/point_rcnn_0/dense_128_all/"
NDT_cfg                      : {'voxel_size': 0.5, 'overlap': True, 'min_pts_voxel': 5, 'noise': 0.05}
NDT_cache_root               : "./data/KITTI/NDT_pkl/det/"
NDT_cache_name               : "point_rcnn_0_cache-128_all" #path for load/write

#---------------AB3DMOT base
use_default                  : False
base_param                   : {'car':{'algm': 'hungar', 'metric': 'giou_3d', 'thres': 0.2, 'min_hits': 5, 'max_age': 40},
                                'cyclist':{'algm': 'hungar', 'metric': 'dist_3d', 'thres': 2.0, 'min_hits': 5, 'max_age': 40}}          
# --------------- DA stage2 threshold
NDT_thres                 : {'car': {'NDT_score': -15000,'max_dist': 6.0,'max_angle': 20},
                                'cyclist': {'NDT_score': -15000,'max_dist': 4.5,'max_angle': 20}}  
two_stage: False                                  
stage2_param                : {'car':{'algm': 'hungar', 'metric': 'dist_3d', 'thres': 3.0},
                                'cyclist':{'algm': 'hungar', 'metric': 'dist_3d', 'thres': 3.0}}    
