##EVALUATION CONFIG
# ------------------- Dataset Name -------------------------
description                  : KITTI
# ------------------- Path Options -------------------------
gt_path                      : "/home/philly12399/thesis/AB3DMOT/scripts/KITTI/label/" 
trk_path                     : "/home/philly12399/philly_ssd/ab3dmot/track_exp/newexp/label"
out_path                     : "/home/philly12399/philly_ssd/ab3dmot/track_exp/newexp/"
calib_path                   : "/home/philly12399/philly_ssd/KITTI_tracking/training/calib/" 
exp_name                     : eval
# ------------------- Eval Options -------------------------
iou                          : 3D
threshold                    : [0.25,0.5]
class_name                   : ['car','cyclist']
gt_format                    : Wayside
trk_format                   : Wayside
num_hypo                     : 1
max_occlusion                : 4
max_truncation               : 2 #0,1,2
eval_seq                     : [21]
fov_filter                   : False