# ------------------- Dataset Name -------------------------
description                  : Wayside
# ------------------- Path Options -------------------------
gt_path                      : "/home/philly12399/evaltest/gt/label/" 
trk_path                     : "/home/philly12399/evaltest/track/label/"
out_path                     : "/home/philly12399/evaltest/wayside_output/"
exp_name                     : test
# ------------------- Eval Options -------------------------
iou                          : 3D
threshold                    : [0.5]
class_name                   : ['car','cyclist']
gt_format                    : Wayside
trk_format                   : Wayside
num_hypo                     : 1
max_occlusion                : 4
eval_seq                     : [4]

